apiVersion: v1
kind: Service
metadata:
  name: login-service
  labels:
    app: uber-clone
spec:
  type: LoadBalancer  # Expose as a LoadBalancer to the internet, change to ClusterIP for internal access
  ports:
  - port: 80  # External port to expose
    targetPort: 5000  # Port inside the container
  selector:
    app: uber-clone
